#theme: jekyll-theme-slate
remote_theme: pages-themes/minimal@v0.2.0

title: "Physical Activity and Technology Hack Day (PhysTech)"
title-short: PhysTech
description: PhysTech is a student-organized online hackathon for anyone who does, watches, analyzes and promotes any physical activities. It takes place annually, usually in the end of June. 

full_url: https://binnovative-boston.github.io/phystech
logo: /images/logo-whitebg-orig.png
devpost_url: https://phystech-2026.devpost.com/
discord_url: https://discord.gg/mt4RVtcA7h
email: mailto:phystech@yahoo.com

show_downloads: false
#google_analytics: 

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

